# Port at which the Service Provider is accessible.
# Changing the port would require you to change the settings of IDP since
# the assertion is sent to the Service Provide URL which will include this port
port: 5678
# Host at which the Service Provider is accessible.
# Changing the host would require you to change the settings of IDP since
# the assertion is sent to the Service Provide URL which will include this host

host: "idp.samltools.com"
# http or https
protocol : "http"
logon_path: "/logon"



